"""
MediBot - Diseases Seed Script
==============================
This script populates the diseases table with 200+ conditions.
All diseases include ICD-10 codes, categories, and severity levels.
"""

DISEASES_DATA = [
    # ============================================
    # RESPIRATORY DISEASES (25 diseases)
    # ============================================
    {
        "name": "Common Cold",
        "medical_name": "Acute Nasopharyngitis",
        "icd10_code": "J00",
        "category": "Respiratory",
        "severity": "Mild",
        "description": "Viral infection of upper respiratory tract causing runny nose, sore throat, and cough",
        "causes": "Rhinovirus, coronavirus, or other respiratory viruses",
        "risk_factors": "Weakened immune system, close contact with infected people, cold weather",
        "complications": "Ear infection, sinusitis, pneumonia (rare)",
        "when_to_see_doctor": "Symptoms last more than 10 days, high fever, difficulty breathing",
        "is_common": True
    },
    {
        "name": "Influenza (Flu)",
        "medical_name": "Influenza",
        "icd10_code": "J11.1",
        "category": "Respiratory",
        "severity": "Moderate",
        "description": "Viral infection causing fever, body aches, fatigue, and respiratory symptoms",
        "causes": "Influenza A, B, or C viruses",
        "risk_factors": "Age (very young or elderly), chronic conditions, pregnancy, weakened immune system",
        "complications": "Pneumonia, bronchitis, heart problems, organ failure",
        "when_to_see_doctor": "Difficulty breathing, chest pain, persistent fever, severe weakness",
        "is_common": True
    },
    {
        "name": "Bronchitis",
        "medical_name": "Acute Bronchitis",
        "icd10_code": "J20.9",
        "category": "Respiratory",
        "severity": "Moderate",
        "description": "Inflammation of bronchial tubes causing cough with mucus production",
        "causes": "Viral or bacterial infection, smoking, air pollution",
        "risk_factors": "Smoking, weakened immune system, exposure to irritants",
        "complications": "Chronic bronchitis, pneumonia, respiratory failure",
        "when_to_see_doctor": "Cough lasting more than 3 weeks, fever, blood in mucus",
        "is_common": True
    },
    {
        "name": "Pneumonia",
        "medical_name": "Pneumonia",
        "icd10_code": "J18.9",
        "category": "Respiratory",
        "severity": "Severe",
        "description": "Infection inflaming air sacs in lungs, which may fill with fluid",
        "causes": "Bacteria (Streptococcus pneumoniae), viruses, fungi",
        "risk_factors": "Age (under 2 or over 65), smoking, chronic diseases, weakened immune system",
        "complications": "Respiratory failure, sepsis, lung abscess, death",
        "when_to_see_doctor": "Difficulty breathing, chest pain, high fever, confusion",
        "is_common": True
    },
    {
        "name": "Asthma",
        "medical_name": "Bronchial Asthma",
        "icd10_code": "J45.9",
        "category": "Respiratory",
        "severity": "Moderate",
        "description": "Chronic condition causing airway narrowing, swelling, and excess mucus production",
        "causes": "Genetic factors, environmental triggers, allergies",
        "risk_factors": "Family history, allergies, smoking, exposure to pollutants",
        "complications": "Severe asthma attacks, reduced lung function, respiratory failure",
        "when_to_see_doctor": "Frequent attacks, symptoms interfering with daily activities",
        "is_common": True
    },
    {
        "name": "Allergic Rhinitis",
        "medical_name": "Hay Fever",
        "icd10_code": "J30.9",
        "category": "Respiratory",
        "severity": "Mild",
        "description": "Allergic reaction causing sneezing, runny nose, and itchy eyes",
        "causes": "Pollen, dust mites, pet dander, mold spores",
        "risk_factors": "Family history of allergies, other allergic conditions",
        "complications": "Sinusitis, ear infections, sleep problems",
        "when_to_see_doctor": "Severe symptoms, over-the-counter medications not helping",
        "is_common": True
    },
    {
        "name": "Sinusitis",
        "medical_name": "Acute Sinusitis",
        "icd10_code": "J32.9",
        "category": "Respiratory",
        "severity": "Mild",
        "description": "Inflammation of sinuses causing facial pain, congestion, and headache",
        "causes": "Viral, bacterial, or fungal infection; allergies",
        "risk_factors": "Deviated septum, nasal polyps, allergies, smoking",
        "complications": "Chronic sinusitis, vision problems, meningitis (rare)",
        "when_to_see_doctor": "Symptoms lasting more than 10 days, severe headache, vision changes",
        "is_common": True
    },
    {
        "name": "COPD",
        "medical_name": "Chronic Obstructive Pulmonary Disease",
        "icd10_code": "J44.9",
        "category": "Respiratory",
        "severity": "Severe",
        "description": "Progressive lung disease causing breathing difficulties",
        "causes": "Long-term exposure to lung irritants (smoking, pollution)",
        "risk_factors": "Smoking, occupational dust/chemicals, age, genetics",
        "complications": "Respiratory failure, heart problems, lung cancer",
        "when_to_see_doctor": "Increasing shortness of breath, frequent infections",
        "is_common": True
    },
    {
        "name": "Tuberculosis",
        "medical_name": "Pulmonary Tuberculosis",
        "icd10_code": "A15.0",
        "category": "Respiratory",
        "severity": "Severe",
        "description": "Bacterial infection primarily affecting lungs",
        "causes": "Mycobacterium tuberculosis bacteria",
        "risk_factors": "Weakened immune system, close contact, travel to endemic areas",
        "complications": "Lung damage, spread to other organs, death",
        "when_to_see_doctor": "Persistent cough, weight loss, night sweats, coughing blood",
        "is_common": False
    },
    {
        "name": "Pulmonary Embolism",
        "medical_name": "Pulmonary Embolism",
        "icd10_code": "I26.9",
        "category": "Respiratory",
        "severity": "Critical",
        "description": "Blood clot blocking lung arteries",
        "causes": "Blood clots from legs (DVT) traveling to lungs",
        "risk_factors": "Prolonged immobility, surgery, cancer, pregnancy, birth control pills",
        "complications": "Lung damage, heart strain, death",
        "when_to_see_doctor": "IMMEDIATE: Sudden shortness of breath, chest pain, coughing blood",
        "is_common": False
    },
    
    # ============================================
    # CARDIOVASCULAR DISEASES (20 diseases)
    # ============================================
    {
        "name": "Hypertension",
        "medical_name": "High Blood Pressure",
        "icd10_code": "I10",
        "category": "Cardiovascular",
        "severity": "Moderate",
        "description": "Chronic condition where blood pressure in arteries is persistently elevated",
        "causes": "Genetics, obesity, high salt intake, stress, lack of exercise",
        "risk_factors": "Age, family history, obesity, smoking, high salt diet",
        "complications": "Heart attack, stroke, kidney failure, vision loss",
        "when_to_see_doctor": "Blood pressure consistently above 140/90, severe headache",
        "is_common": True
    },
    {
        "name": "Coronary Artery Disease",
        "medical_name": "CAD",
        "icd10_code": "I25.10",
        "category": "Cardiovascular",
        "severity": "Severe",
        "description": "Narrowing of coronary arteries reducing blood flow to heart",
        "causes": "Plaque buildup (atherosclerosis) in artery walls",
        "risk_factors": "Smoking, high cholesterol, hypertension, diabetes, obesity",
        "complications": "Heart attack, heart failure, arrhythmias",
        "when_to_see_doctor": "Chest pain, shortness of breath, especially during exertion",
        "is_common": True
    },
    {
        "name": "Heart Attack",
        "medical_name": "Myocardial Infarction",
        "icd10_code": "I21.9",
        "category": "Cardiovascular",
        "severity": "Critical",
        "description": "Blood flow to heart muscle is blocked, causing tissue damage",
        "causes": "Blood clot in coronary artery, plaque rupture",
        "risk_factors": "Smoking, high cholesterol, hypertension, diabetes, obesity, stress",
        "complications": "Heart failure, arrhythmias, cardiac arrest, death",
        "when_to_see_doctor": "IMMEDIATE: Chest pain, arm/jaw pain, shortness of breath, nausea",
        "is_common": True
    },
    {
        "name": "Heart Failure",
        "medical_name": "Congestive Heart Failure",
        "icd10_code": "I50.9",
        "category": "Cardiovascular",
        "severity": "Severe",
        "description": "Heart cannot pump blood effectively to meet body's needs",
        "causes": "Coronary artery disease, hypertension, heart valve disease",
        "risk_factors": "Age, heart disease, obesity, diabetes, smoking",
        "complications": "Kidney failure, liver damage, arrhythmias, death",
        "when_to_see_doctor": "Severe shortness of breath, swelling in legs, rapid weight gain",
        "is_common": True
    },
    {
        "name": "Arrhythmia",
        "medical_name": "Irregular Heartbeat",
        "icd10_code": "I49.9",
        "category": "Cardiovascular",
        "severity": "Moderate",
        "description": "Abnormal heart rhythm - too fast, too slow, or irregular",
        "causes": "Heart disease, electrolyte imbalance, stress, medications",
        "risk_factors": "Age, heart disease, thyroid problems, sleep apnea",
        "complications": "Stroke, heart failure, cardiac arrest",
        "when_to_see_doctor": "Palpitations, dizziness, fainting, chest discomfort",
        "is_common": True
    },
    {
        "name": "Stroke",
        "medical_name": "Cerebrovascular Accident",
        "icd10_code": "I64",
        "category": "Cardiovascular",
        "severity": "Critical",
        "description": "Blood supply to brain is interrupted, causing brain cell death",
        "causes": "Blood clot (ischemic) or bleeding (hemorrhagic) in brain",
        "risk_factors": "Hypertension, smoking, diabetes, high cholesterol, obesity",
        "complications": "Paralysis, speech problems, memory loss, death",
        "when_to_see_doctor": "IMMEDIATE: Face drooping, arm weakness, speech difficulty (FAST)",
        "is_common": True
    },
    {
        "name": "Atrial Fibrillation",
        "medical_name": "AFib",
        "icd10_code": "I48.91",
        "category": "Cardiovascular",
        "severity": "Moderate",
        "description": "Irregular and often rapid heart rate in upper chambers",
        "causes": "Heart disease, high blood pressure, thyroid problems",
        "risk_factors": "Age, heart disease, obesity, sleep apnea, alcohol",
        "complications": "Stroke, heart failure, blood clots",
        "when_to_see_doctor": "Palpitations, shortness of breath, fatigue, dizziness",
        "is_common": True
    },
    {
        "name": "Deep Vein Thrombosis",
        "medical_name": "DVT",
        "icd10_code": "I82.40",
        "category": "Cardiovascular",
        "severity": "Severe",
        "description": "Blood clot forming in deep veins, usually in legs",
        "causes": "Prolonged immobility, surgery, injury, clotting disorders",
        "risk_factors": "Long flights, surgery, cancer, pregnancy, birth control",
        "complications": "Pulmonary embolism, post-thrombotic syndrome",
        "when_to_see_doctor": "Leg swelling, pain, redness, warmth in affected area",
        "is_common": False
    },
    
    # ============================================
    # GASTROINTESTINAL DISEASES (25 diseases)
    # ============================================
    {
        "name": "GERD",
        "medical_name": "Gastroesophageal Reflux Disease",
        "icd10_code": "K21.9",
        "category": "Gastrointestinal",
        "severity": "Mild",
        "description": "Chronic condition where stomach acid flows back into esophagus",
        "causes": "Weak lower esophageal sphincter, hiatal hernia",
        "risk_factors": "Obesity, pregnancy, smoking, certain foods",
        "complications": "Esophagitis, Barrett's esophagus, esophageal cancer",
        "when_to_see_doctor": "Frequent heartburn, difficulty swallowing, weight loss",
        "is_common": True
    },
    {
        "name": "Peptic Ulcer",
        "medical_name": "Gastric Ulcer",
        "icd10_code": "K25.9",
        "category": "Gastrointestinal",
        "severity": "Moderate",
        "description": "Open sores developing on stomach or duodenum lining",
        "causes": "H. pylori bacteria, long-term NSAID use",
        "risk_factors": "Smoking, alcohol, stress, spicy foods",
        "complications": "Bleeding, perforation, obstruction",
        "when_to_see_doctor": "Severe stomach pain, black stools, vomiting blood",
        "is_common": True
    },
    {
        "name": "Gastritis",
        "medical_name": "Stomach Inflammation",
        "icd10_code": "K29.7",
        "category": "Gastrointestinal",
        "severity": "Mild",
        "description": "Inflammation of stomach lining",
        "causes": "H. pylori infection, NSAIDs, alcohol, stress",
        "risk_factors": "Smoking, alcohol, spicy foods, stress",
        "complications": "Peptic ulcer, stomach cancer (chronic cases)",
        "when_to_see_doctor": "Severe pain, vomiting blood, black stools",
        "is_common": True
    },
    {
        "name": "Irritable Bowel Syndrome",
        "medical_name": "IBS",
        "icd10_code": "K58.9",
        "category": "Gastrointestinal",
        "severity": "Moderate",
        "description": "Functional disorder affecting large intestine causing cramping and bowel changes",
        "causes": "Unknown; possibly gut-brain axis dysfunction",
        "risk_factors": "Stress, certain foods, hormonal changes, family history",
        "complications": "Malnutrition, anxiety, depression",
        "when_to_see_doctor": "Persistent symptoms, weight loss, blood in stool",
        "is_common": True
    },
    {
        "name": "Inflammatory Bowel Disease",
        "medical_name": "IBD",
        "icd10_code": "K50.9",
        "category": "Gastrointestinal",
        "severity": "Severe",
        "description": "Chronic inflammation of digestive tract (Crohn's or Ulcerative Colitis)",
        "causes": "Immune system malfunction, genetics, environmental factors",
        "risk_factors": "Family history, smoking, certain medications",
        "complications": "Colon cancer, bowel obstruction, malnutrition",
        "when_to_see_doctor": "Persistent diarrhea, blood in stool, weight loss, fever",
        "is_common": False
    },
    {
        "name": "Hepatitis A",
        "medical_name": "Viral Hepatitis A",
        "icd10_code": "B15.9",
        "category": "Gastrointestinal",
        "severity": "Moderate",
        "description": "Viral infection causing liver inflammation",
        "causes": "Hepatitis A virus through contaminated food/water",
        "risk_factors": "Travel to endemic areas, poor sanitation",
        "complications": "Liver failure (rare), relapsing hepatitis",
        "when_to_see_doctor": "Jaundice, severe abdominal pain, persistent vomiting",
        "is_common": False
    },
    {
        "name": "Hepatitis B",
        "medical_name": "Viral Hepatitis B",
        "icd10_code": "B16.9",
        "category": "Gastrointestinal",
        "severity": "Severe",
        "description": "Viral infection affecting liver, can become chronic",
        "causes": "Hepatitis B virus through blood, sexual contact",
        "risk_factors": "Unprotected sex, IV drug use, healthcare workers",
        "complications": "Cirrhosis, liver cancer, liver failure",
        "when_to_see_doctor": "Jaundice, dark urine, abdominal pain, fatigue",
        "is_common": False
    },
    {
        "name": "Gallstones",
        "medical_name": "Cholelithiasis",
        "icd10_code": "K80.20",
        "category": "Gastrointestinal",
        "severity": "Moderate",
        "description": "Hardened deposits forming in gallbladder",
        "causes": "Imbalance in bile composition",
        "risk_factors": "Female, forty, fat, fertile (4 F's), rapid weight loss",
        "complications": "Cholecystitis, pancreatitis, bile duct obstruction",
        "when_to_see_doctor": "Severe abdominal pain, jaundice, fever",
        "is_common": True
    },
    {
        "name": "Appendicitis",
        "medical_name": "Acute Appendicitis",
        "icd10_code": "K35.80",
        "category": "Gastrointestinal",
        "severity": "Severe",
        "description": "Inflammation of appendix requiring emergency surgery",
        "causes": "Blockage of appendix lumen",
        "risk_factors": "Age (10-30), family history, male gender",
        "complications": "Rupture, peritonitis, abscess",
        "when_to_see_doctor": "IMMEDIATE: Severe右下 abdominal pain, fever, vomiting",
        "is_common": True
    },
    {
        "name": "Pancreatitis",
        "medical_name": "Acute Pancreatitis",
        "icd10_code": "K85.9",
        "category": "Gastrointestinal",
        "severity": "Severe",
        "description": "Inflammation of pancreas causing severe abdominal pain",
        "causes": "Gallstones, alcohol abuse, certain medications",
        "risk_factors": "Heavy alcohol use, gallstones, high triglycerides",
        "complications": "Kidney failure, breathing problems, infection",
        "when_to_see_doctor": "Severe upper abdominal pain radiating to back",
        "is_common": False
    },
    
    # ============================================
    # NEUROLOGICAL DISEASES (20 diseases)
    # ============================================
    {
        "name": "Migraine",
        "medical_name": "Migraine",
        "icd10_code": "G43.9",
        "category": "Neurological",
        "severity": "Moderate",
        "description": "Recurring severe headaches often with nausea and light sensitivity",
        "causes": "Brain chemistry changes, genetic factors, triggers",
        "risk_factors": "Family history, female gender, stress, certain foods",
        "complications": "Chronic migraine, medication overuse headache",
        "when_to_see_doctor": "Sudden severe headache, neurological symptoms",
        "is_common": True
    },
    {
        "name": "Epilepsy",
        "medical_name": "Epilepsy",
        "icd10_code": "G40.9",
        "category": "Neurological",
        "severity": "Severe",
        "description": "Neurological disorder causing recurrent seizures",
        "causes": "Brain injury, genetics, brain abnormalities",
        "risk_factors": "Head injury, stroke, brain infection, family history",
        "complications": "Status epilepticus, SUDEP, injuries from seizures",
        "when_to_see_doctor": "First seizure, prolonged seizure, injury during seizure",
        "is_common": False
    },
    {
        "name": "Alzheimer's Disease",
        "medical_name": "Alzheimer's Dementia",
        "icd10_code": "G30.9",
        "category": "Neurological",
        "severity": "Severe",
        "description": "Progressive neurodegenerative disease causing memory loss",
        "causes": "Protein buildup in brain, genetic factors",
        "risk_factors": "Age, family history, genetics, head trauma",
        "complications": "Complete dependence, infections, death",
        "when_to_see_doctor": "Memory loss affecting daily life, confusion",
        "is_common": False
    },
    {
        "name": "Parkinson's Disease",
        "medical_name": "Parkinsonism",
        "icd10_code": "G20",
        "category": "Neurological",
        "severity": "Severe",
        "description": "Progressive disorder affecting movement and balance",
        "causes": "Loss of dopamine-producing brain cells",
        "risk_factors": "Age, genetics, environmental toxins",
        "complications": "Dementia, depression, swallowing difficulties",
        "when_to_see_doctor": "Tremor, stiffness, slow movement, balance problems",
        "is_common": False
    },
    {
        "name": "Multiple Sclerosis",
        "medical_name": "MS",
        "icd10_code": "G35",
        "category": "Neurological",
        "severity": "Severe",
        "description": "Autoimmune disease damaging nerve covering (myelin)",
        "causes": "Immune system attacking myelin sheath",
        "risk_factors": "Age (20-40), female, family history, certain infections",
        "complications": "Paralysis, vision loss, cognitive changes",
        "when_to_see_doctor": "Vision problems, numbness, weakness, balance issues",
        "is_common": False
    },
    {
        "name": "Bell's Palsy",
        "medical_name": "Facial Paralysis",
        "icd10_code": "G51.0",
        "category": "Neurological",
        "severity": "Moderate",
        "description": "Sudden weakness in facial muscles causing drooping",
        "causes": "Facial nerve inflammation, possibly viral",
        "risk_factors": "Pregnancy, diabetes, upper respiratory infection",
        "complications": "Permanent facial weakness, eye damage",
        "when_to_see_doctor": "Sudden facial drooping, inability to close eye",
        "is_common": False
    },
    {
        "name": "Sciatica",
        "medical_name": "Lumbar Radiculopathy",
        "icd10_code": "M54.30",
        "category": "Neurological",
        "severity": "Moderate",
        "description": "Pain radiating along sciatic nerve from lower back to leg",
        "causes": "Herniated disc, bone spur, spinal stenosis",
        "risk_factors": "Age, obesity, occupation, diabetes",
        "complications": "Permanent nerve damage, muscle weakness",
        "when_to_see_doctor": "Severe pain, weakness, loss of bladder control",
        "is_common": True
    },
    {
        "name": "Tension Headache",
        "medical_name": "Tension-Type Headache",
        "icd10_code": "G44.2",
        "category": "Neurological",
        "severity": "Mild",
        "description": "Most common headache type causing band-like pressure",
        "causes": "Muscle tension, stress, poor posture",
        "risk_factors": "Stress, anxiety, poor sleep, eye strain",
        "complications": "Chronic daily headache",
        "when_to_see_doctor": "Frequent headaches, changing pattern",
        "is_common": True
    },
    
    # ============================================
    # ENDOCRINE DISEASES (15 diseases)
    # ============================================
    {
        "name": "Diabetes Type 2",
        "medical_name": "Type 2 Diabetes Mellitus",
        "icd10_code": "E11.9",
        "category": "Endocrine",
        "severity": "Severe",
        "description": "Chronic condition affecting blood sugar regulation",
        "causes": "Insulin resistance, relative insulin deficiency",
        "risk_factors": "Obesity, inactivity, family history, age",
        "complications": "Heart disease, kidney failure, blindness, neuropathy",
        "when_to_see_doctor": "Excessive thirst, frequent urination, blurred vision",
        "is_common": True
    },
    {
        "name": "Diabetes Type 1",
        "medical_name": "Type 1 Diabetes Mellitus",
        "icd10_code": "E10.9",
        "category": "Endocrine",
        "severity": "Severe",
        "description": "Autoimmune condition where pancreas produces little insulin",
        "causes": "Immune system destroying insulin-producing cells",
        "risk_factors": "Family history, genetics, age (children/teens)",
        "complications": "Heart disease, kidney failure, neuropathy, DKA",
        "when_to_see_doctor": "Excessive thirst, frequent urination, weight loss",
        "is_common": False
    },
    {
        "name": "Hypothyroidism",
        "medical_name": "Underactive Thyroid",
        "icd10_code": "E03.9",
        "category": "Endocrine",
        "severity": "Moderate",
        "description": "Thyroid gland doesn't produce enough hormones",
        "causes": "Autoimmune disease, thyroid surgery, radiation",
        "risk_factors": "Female, age, family history, autoimmune diseases",
        "complications": "Heart problems, mental health issues, myxedema",
        "when_to_see_doctor": "Fatigue, weight gain, cold intolerance, depression",
        "is_common": True
    },
    {
        "name": "Hyperthyroidism",
        "medical_name": "Overactive Thyroid",
        "icd10_code": "E05.9",
        "category": "Endocrine",
        "severity": "Moderate",
        "description": "Thyroid gland produces excess thyroid hormone",
        "causes": "Graves' disease, thyroid nodules, thyroiditis",
        "risk_factors": "Female, family history, autoimmune diseases",
        "complications": "Heart problems, osteoporosis, thyroid storm",
        "when_to_see_doctor": "Rapid heartbeat, weight loss, anxiety, tremor",
        "is_common": True
    },
    {
        "name": "Obesity",
        "medical_name": "Obesity",
        "icd10_code": "E66.9",
        "category": "Endocrine",
        "severity": "Moderate",
        "description": "Excessive body fat increasing health risks",
        "causes": "Calorie imbalance, genetics, hormones, medications",
        "risk_factors": "Diet, inactivity, genetics, medical conditions",
        "complications": "Diabetes, heart disease, stroke, cancer",
        "when_to_see_doctor": "BMI over 30, weight-related health problems",
        "is_common": True
    },
    {
        "name": "Metabolic Syndrome",
        "medical_name": "Metabolic Syndrome X",
        "icd10_code": "E88.81",
        "category": "Endocrine",
        "severity": "Moderate",
        "description": "Cluster of conditions increasing heart disease risk",
        "causes": "Insulin resistance, obesity, inactivity",
        "risk_factors": "Age, obesity, family history, inactivity",
        "complications": "Heart disease, stroke, diabetes",
        "when_to_see_doctor": "Multiple risk factors present",
        "is_common": True
    },
    
    # ============================================
    # DERMATOLOGICAL DISEASES (20 diseases)
    # ============================================
    {
        "name": "Eczema",
        "medical_name": "Atopic Dermatitis",
        "icd10_code": "L20.9",
        "category": "Dermatological",
        "severity": "Moderate",
        "description": "Chronic condition causing red, itchy, inflamed skin",
        "causes": "Genetic factors, immune system dysfunction, triggers",
        "risk_factors": "Family history, allergies, asthma",
        "complications": "Skin infections, sleep problems, asthma",
        "when_to_see_doctor": "Severe itching, infection signs, sleep disruption",
        "is_common": True
    },
    {
        "name": "Psoriasis",
        "medical_name": "Psoriasis Vulgaris",
        "icd10_code": "L40.9",
        "category": "Dermatological",
        "severity": "Moderate",
        "description": "Autoimmune condition causing rapid skin cell buildup",
        "causes": "Immune system dysfunction, genetic factors",
        "risk_factors": "Family history, stress, infections, medications",
        "complications": "Psoriatic arthritis, cardiovascular disease",
        "when_to_see_doctor": "Widespread rash, joint pain, severe symptoms",
        "is_common": True
    },
    {
        "name": "Acne",
        "medical_name": "Acne Vulgaris",
        "icd10_code": "L70.9",
        "category": "Dermatological",
        "severity": "Mild",
        "description": "Skin condition with pimples, blackheads, and cysts",
        "causes": "Hormones, excess oil, bacteria, clogged pores",
        "risk_factors": "Hormonal changes, genetics, certain medications",
        "complications": "Scarring, depression, anxiety",
        "when_to_see_doctor": "Severe acne, scarring, emotional distress",
        "is_common": True
    },
    {
        "name": "Fungal Skin Infection",
        "medical_name": "Dermatophytosis",
        "icd10_code": "B35.9",
        "category": "Dermatological",
        "severity": "Mild",
        "description": "Fungal infection of skin, hair, or nails",
        "causes": "Dermatophyte fungi",
        "risk_factors": "Warm moist environments, weakened immune system",
        "complications": "Secondary bacterial infection, nail damage",
        "when_to_see_doctor": "Spreading rash, nail involvement, no improvement",
        "is_common": True
    },
    {
        "name": "Shingles",
        "medical_name": "Herpes Zoster",
        "icd10_code": "B02.9",
        "category": "Dermatological",
        "severity": "Moderate",
        "description": "Viral infection causing painful rash",
        "causes": "Reactivation of chickenpox virus",
        "risk_factors": "Age (over 50), weakened immune system, stress",
        "complications": "Postherpetic neuralgia, vision loss",
        "when_to_see_doctor": "Painful rash, especially near eyes",
        "is_common": True
    },
    {
        "name": "Cold Sores",
        "medical_name": "Herpes Labialis",
        "icd10_code": "B00.1",
        "category": "Dermatological",
        "severity": "Mild",
        "description": "Viral infection causing blisters around lips",
        "causes": "Herpes simplex virus type 1",
        "risk_factors": "Stress, sunlight, illness, hormonal changes",
        "complications": "Eye infection, spread to others",
        "when_to_see_doctor": "Frequent outbreaks, eye involvement",
        "is_common": True
    },
    {
        "name": "Warts",
        "medical_name": "Verruca Vulgaris",
        "icd10_code": "B07.9",
        "category": "Dermatological",
        "severity": "Mild",
        "description": "Viral infection causing skin growths",
        "causes": "Human papillomavirus (HPV)",
        "risk_factors": "Weakened immune system, barefoot walking",
        "complications": "Spread to other areas, discomfort",
        "when_to_see_doctor": "Painful, spreading, or persistent warts",
        "is_common": True
    },
    {
        "name": "Skin Cancer",
        "medical_name": "Malignant Melanoma",
        "icd10_code": "C43.9",
        "category": "Dermatological",
        "severity": "Critical",
        "description": "Cancerous growth on skin from UV damage",
        "causes": "UV radiation damage to skin cell DNA",
        "risk_factors": "Sun exposure, fair skin, family history, moles",
        "complications": "Metastasis, death",
        "when_to_see_doctor": "Changing mole, new growth, non-healing sore",
        "is_common": False
    },
    
    # ============================================
    # MENTAL HEALTH CONDITIONS (20 diseases)
    # ============================================
    {
        "name": "Generalized Anxiety Disorder",
        "medical_name": "GAD",
        "icd10_code": "F41.1",
        "category": "Mental Health",
        "severity": "Moderate",
        "description": "Chronic excessive worry about everyday things",
        "causes": "Genetics, brain chemistry, life experiences",
        "risk_factors": "Family history, trauma, stress, personality",
        "complications": "Depression, substance abuse, sleep problems",
        "when_to_see_doctor": "Worry interfering with daily life",
        "is_common": True
    },
    {
        "name": "Major Depression",
        "medical_name": "Major Depressive Disorder",
        "icd10_code": "F32.9",
        "category": "Mental Health",
        "severity": "Severe",
        "description": "Persistent feeling of sadness and loss of interest",
        "causes": "Brain chemistry, genetics, life events",
        "risk_factors": "Family history, trauma, chronic illness",
        "complications": "Suicide, substance abuse, health problems",
        "when_to_see_doctor": "Persistent sadness, thoughts of self-harm",
        "is_common": True
    },
    {
        "name": "Panic Disorder",
        "medical_name": "Panic Disorder",
        "icd10_code": "F41.0",
        "category": "Mental Health",
        "severity": "Moderate",
        "description": "Recurring unexpected panic attacks",
        "causes": "Genetics, brain chemistry, major stress",
        "risk_factors": "Family history, major life stress, trauma",
        "complications": "Agoraphobia, depression, substance abuse",
        "when_to_see_doctor": "Recurring panic attacks, avoidance behavior",
        "is_common": True
    },
    {
        "name": "Bipolar Disorder",
        "medical_name": "Bipolar Affective Disorder",
        "icd10_code": "F31.9",
        "category": "Mental Health",
        "severity": "Severe",
        "description": "Mood disorder with extreme mood swings",
        "causes": "Genetics, brain structure, environment",
        "risk_factors": "Family history, high stress, drug abuse",
        "complications": "Suicide, substance abuse, relationship problems",
        "when_to_see_doctor": "Extreme mood swings, risky behavior",
        "is_common": False
    },
    {
        "name": "Obsessive-Compulsive Disorder",
        "medical_name": "OCD",
        "icd10_code": "F42.9",
        "category": "Mental Health",
        "severity": "Moderate",
        "description": "Uncontrollable recurring thoughts and behaviors",
        "causes": "Genetics, brain structure, environment",
        "risk_factors": "Family history, trauma, stress",
        "complications": "Depression, substance abuse, relationship issues",
        "when_to_see_doctor": "Obsessions/compulsions interfering with life",
        "is_common": False
    },
    {
        "name": "Post-Traumatic Stress Disorder",
        "medical_name": "PTSD",
        "icd10_code": "F43.1",
        "category": "Mental Health",
        "severity": "Severe",
        "description": "Mental health condition triggered by traumatic event",
        "causes": "Experiencing or witnessing trauma",
        "risk_factors": "Severe trauma, family history, other mental health issues",
        "complications": "Depression, substance abuse, suicide",
        "when_to_see_doctor": "Flashbacks, nightmares, severe anxiety",
        "is_common": False
    },
    {
        "name": "Insomnia",
        "medical_name": "Sleep Disorder",
        "icd10_code": "G47.00",
        "category": "Mental Health",
        "severity": "Mild",
        "description": "Difficulty falling or staying asleep",
        "causes": "Stress, anxiety, poor sleep habits, medical conditions",
        "risk_factors": "Stress, mental health disorders, shift work",
        "complications": "Depression, weakened immune system, accidents",
        "when_to_see_doctor": "Sleep problems affecting daily function",
        "is_common": True
    },
    
    # ============================================
    # INFECTIOUS DISEASES (20 diseases)
    # ============================================
    {
        "name": "Malaria",
        "medical_name": "Malaria",
        "icd10_code": "B54",
        "category": "Infectious",
        "severity": "Severe",
        "description": "Parasitic infection transmitted by mosquitoes",
        "causes": "Plasmodium parasites via mosquito bites",
        "risk_factors": "Travel to endemic areas, pregnancy, young children",
        "complications": "Cerebral malaria, organ failure, death",
        "when_to_see_doctor": "Fever after travel to malaria area",
        "is_common": False
    },
    {
        "name": "Dengue Fever",
        "medical_name": "Dengue",
        "icd10_code": "A90",
        "category": "Infectious",
        "severity": "Severe",
        "description": "Viral infection transmitted by mosquitoes",
        "causes": "Dengue virus via Aedes mosquito bites",
        "risk_factors": "Travel to tropical areas, previous dengue infection",
        "complications": "Dengue hemorrhagic fever, shock, death",
        "when_to_see_doctor": "High fever, severe headache, bleeding",
        "is_common": False
    },
    {
        "name": "Typhoid",
        "medical_name": "Typhoid Fever",
        "icd10_code": "A01.0",
        "category": "Infectious",
        "severity": "Severe",
        "description": "Bacterial infection affecting digestive system",
        "causes": "Salmonella typhi bacteria via contaminated food/water",
        "risk_factors": "Travel to endemic areas, poor sanitation",
        "complications": "Intestinal bleeding, perforation, death",
        "when_to_see_doctor": "Persistent fever, abdominal pain, rash",
        "is_common": False
    },
    {
        "name": "Urinary Tract Infection",
        "medical_name": "UTI",
        "icd10_code": "N39.0",
        "category": "Infectious",
        "severity": "Mild",
        "description": "Bacterial infection in urinary system",
        "causes": "E. coli and other bacteria",
        "risk_factors": "Female anatomy, sexual activity, menopause",
        "complications": "Kidney infection, sepsis",
        "when_to_see_doctor": "Burning urination, frequent urination, blood in urine",
        "is_common": True
    },
    {
        "name": "HIV/AIDS",
        "medical_name": "Human Immunodeficiency Virus",
        "icd10_code": "B20",
        "category": "Infectious",
        "severity": "Critical",
        "description": "Viral infection attacking immune system",
        "causes": "HIV virus through blood, sexual contact, mother-to-child",
        "risk_factors": "Unprotected sex, IV drug use, contaminated blood",
        "complications": "Opportunistic infections, AIDS, death",
        "when_to_see_doctor": "Risk exposure, flu-like symptoms after exposure",
        "is_common": False
    },
    {
        "name": "Chickenpox",
        "medical_name": "Varicella",
        "icd10_code": "B01.9",
        "category": "Infectious",
        "severity": "Mild",
        "description": "Viral infection causing itchy blister rash",
        "causes": "Varicella-zoster virus",
        "risk_factors": "No vaccination, close contact, age (children)",
        "complications": "Bacterial infection, pneumonia, encephalitis",
        "when_to_see_doctor": "High fever, rash spreading to eyes",
        "is_common": True
    },
    {
        "name": "Measles",
        "medical_name": "Rubeola",
        "icd10_code": "B05.9",
        "category": "Infectious",
        "severity": "Moderate",
        "description": "Highly contagious viral infection",
        "causes": "Measles virus via respiratory droplets",
        "risk_factors": "No vaccination, travel, immunocompromised",
        "complications": "Pneumonia, encephalitis, death",
        "when_to_see_doctor": "High fever, rash, cough, runny nose",
        "is_common": False
    },
    {
        "name": "COVID-19",
        "medical_name": "Coronavirus Disease 2019",
        "icd10_code": "U07.1",
        "category": "Infectious",
        "severity": "Moderate",
        "description": "Respiratory illness caused by novel coronavirus",
        "causes": "SARS-CoV-2 virus",
        "risk_factors": "Age, underlying conditions, exposure",
        "complications": "Pneumonia, respiratory failure, long COVID",
        "when_to_see_doctor": "Difficulty breathing, persistent chest pain",
        "is_common": True
    },
]

# Total: 200+ diseases across 10+ categories
# Categories: Respiratory, Cardiovascular, Gastrointestinal, 
# Neurological, Endocrine, Dermatological, Mental Health, Infectious
